### ISSUE TITLE
import error running pilasengine

### ISSUE THREAD

**Issue by echevemaster** [hugoruscitti/pilas#256]
I've packed pilas for fedora, but when I'll running the application, I've received an import error.

```bash
Traceback (most recent call last):
  File "/usr/bin/pilasengine", line 12, in <module>
    import pilasengine
  File "/usr/lib/python2.7/site-packages/pilasengine/__init__.py", line 20, in <module>
    import configuracion
ImportError: No module named configuracion
```
doing unusable the application

**Comment by echevemaster** [comment]
still is occurring.

**Comment by hugoruscitti** [comment]
m... i can't reproduce it... do you have a minimal example to reproduce it?

**Comment by echevemaster** [comment]
I've taken this commit 4b0c325aee0f1298193517b348a942a0ce11d3b2; I've downloaded thereby

```bash
wget -N https://github.com/hugoruscitti/pilas/archive/4b0c325aee0f1298193517b348a942a0ce11d3b2/pilas-4b0c325aee0f1298193517b348a942a0ce11d3b2.tar.gz

tar xvfz pilas-4b0c325aee0f1298193517b348a942a0ce11d3b2.tar.gz

cd pilas-4b0c325aee0f1298193517b348a942a0ce11d3b2/

python setup.py build

python setup.py install
```

I run pilasengine

and the import error still is there.

**Comment by echevemaster** [comment]
Btw, about the way of download the commit is because fedora have guidelines when you download the source from github or any control version system. http://fedoraproject.org/wiki/Packaging:SourceURL#Github

**Comment by echevemaster** [comment]
Any update here?

**Comment by hugoruscitti** [comment]
hi @echevemaster , it's fixed now, it's related to the setup.py file https://github.com/hugoruscitti/pilas/issues/276
