### ISSUE TITLE
radio_de_colision en pilas.actores.Caja explota

### ISSUE THREAD

**Issue by humitos** [hugoruscitti/pilas#258]
Forma de reproducirlo:

```
caja = pilas.actores.Caja()
caja.radio_de_colision = 20
-310
```

Version de pilas: 0.90.28

**Comment by hugoruscitti** [comment]
Ahí pude resolverlo, el tema venía porque la caja tiene una habilidad llamada "imitar" apuntando
a la figura de colisión. Cuando le cambiamos el area de colisión, la habilidad queda apuntando
a la figura anterior (el rectángulo).

Ahora quedó así, cuando definimos un radio de colisión para la caja, se elimina la figura
de colisión anterior, se desvincula la habilidad Imitar y luego se coloca la nueva area de colisión (un
círculo en este caso).

De todas formas, si tu idea es cambiar el tamaño de la caja, se puede acceder a la figura
física sin reemplazarla por otra:

```
p = pilas.actores.Pelota()
p.figura_de_colision.ancho = 100
p.figura_de_colision.alto = 250
```

Seguramente le siga dando un par de vueltas a este issue, hay varios casos que no contemplé :(

(lo dejo close por ahora), gracias @humitos por el feedback !
