### ISSUE TITLE
Editor texto: Imposible eliminar caracteres unicode que estén a un lado de corchetes

### ISSUE THREAD

**Issue by irvingprog** [hugoruscitti/pilas#281]
En el editor de texto o en la consola, al escribir alguna de los siguientes casos:

- [¿]
- "¿"
- {þ}

o cualquier caracterer unicode entre los corchetes o comillas y tratar de eliminarlo; salta el siguiente error:

<code>
Traceback (most recent call last):
  File "/pilas/pilasengine/interprete/lanas.py", line 345, in keyPressEvent
    self._eliminar_pares_de_caracteres()
  File "/pilas/pilasengine/interprete/editorbase/autocomplete.py", line 151, in _eliminar_pares_de_caracteres
    char = str(line[position])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfe' in position 0: ordinal not in range(128)
</code>

<b>Consejo para solucionarlo</b>

En el archivo /pilas/pilasengine/interprete/editorbase/autocomplete.py en el método <code>_eliminar_pares_de_caracteres</code> en lugar de de convertir a <code>str</code>; convertir a <code>unicode</code>: lineas 151 y 152

**Comment by arkhan** [comment]
@hugoruscitti me gustaría añadir una función para evitar los líos con los caracteres unicode, este error en odoo esta solucionado y se podria usar aqui, si no hay inconveniente en incoporarlo, dime en que archivo lo puedo incoporar para que sea usado en luagar de "str"

**Comment by hugoruscitti** [comment]
Muchas gracias @irvingprog , ahí pude subir el arreglo.

@arkhan, recién veo tu mensaje... para corregir y/o subir cambios en pilas lo mejor es que hagas un fork del repositorio y haciendo luego un pull request.

Hay una documentación bastante copada https://guides.github.com/activities/forking/ que tal vez podríamos traducir y/o rediseñar para colaboradores de pilas. ¿cómo lo ves?
