### ISSUE TITLE
Crear una función para forzar la inicialización del audio

### ISSUE THREAD

**Issue by hugoruscitti** [hugoruscitti/pilas#291]

**Comment by hugoruscitti** [comment]
@DiegoAccorinti fijate que esto puede servir para tu juego. Está documentado acá http://manual.pilas-engine.com.ar/sonidos/#audio-deshabilitado-o-habilitado y va a venir por omisión en pilas 1.4.8 (que se va a publicar en unos días, por ahora solo está en strider).

**Comment by DiegoAccorinti** [comment]
Excelente @hugoruscitti !  gracias por el parche.  Ya le agregué las líneas a TierraLuna.
