### ISSUE TITLE
Actores no garbagecolectados

### ISSUE THREAD

**Issue by jjconti** [hugoruscitti/pilas#302]
Hola!

Si hago

```
mono = pilas.actores.Mono()
mono = pilas.actores.Aceituna()
```

el mono se sigue viendo en la pantalla pero ya no puedo cambiarlo porque no hay más variables que lo referencien. Es este el comportamiento correcto o debería desaparecer de la pantalla si la cuenta de variables que lo apuntan llega a cero?

Saludos,

**Comment by irvingprog** [comment]
Hola @jjconti 

Respuesta corta: Es el comportamiento esperado.

Respuesta larga: 

Es el comportamiento esperado, debido a que Pilas, internamente, sigue manteniendo referencia al actor previamente creado. 

Cuando creas una nueva instancia de la clase Actor, Pilas hace algunos "trucos" de forma interna, por ejemplo, enlazar nuestro actor a la Escena Actual.

https://github.com/hugoruscitti/pilas/blob/develop/pilasengine/actores/actor.py#L142

https://github.com/hugoruscitti/pilas/blob/develop/pilasengine/actores/__init__.py#L161

En la Escena Actual mantenemos una lista de los actores existentes en dicha escena, eso permite que el actor creado siga referenciado, apesar de que la variable, a la cual cómo usuario lo referenciamos, apunte a otro objeto.
 
La forma correcta para eliminar un Actor en Pilas es:

```
mono = pilas.atores.Mono()
mono.eliminar()
```

Además, existe una funcionalidad para a tener acceso a un actor, para el cual se perdio su referencia por el caso que mencionas. @hugoruscitti  nos puede ayudar.

Saludos..

**Comment by hugoruscitti** [comment]
Efectivamente, como menciona @irvingprog, es algo esperado. Notamos que esto incluso está bueno, porque les permite a los chicos caer en la necesidad de "darle nombre" a los actores para poder modificarlos después (y por ende surge la necesidad de aprender acerca de referencias o variables).

Por otro lado, llegado el caso que se genere un actor en pantalla y se quiera recuperar la referencia, hay dos formas:

Desde el intérprete se puede abrir el panel de actores, ahí aparecen todos los actores en la escena, si haces click sobre alguno de ellos se va a mostrar en la pantalla de pilas que ese actor "parpadea" y en el intérprete se va a crear una referencia llamada "actor" para acceder a ese actor seleccionado:

![windows 10 guest additions y chrome running 2017-11-22 09-50-43](https://user-images.githubusercontent.com/99183/33129699-9dab4922-cf6f-11e7-98ae-924127df772a.png)


Otra opción es usar la api de pilas directamente, por ejemplo, para obtener todos los actores
de la escena se puede escribir algo así:

```
pilas.escena_actual()._actores
```

Esa función te va a retornar un grupo, que se usa de manera similar a una lista en realidad.

PD: me gustaría que sea un poco más sencillo acceder a la lista de actores, y que no se acceda a "_actores" directamente de la escena (que es semi-privado digamos). Voy a armar un issue para mejorarlo.
