### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by aurea1123** [hugoruscitti/pilas#314]
Me gusto el proyecto incluso me gustaria poder hacer un videojuego en ello 
Antentamente:
ei.neocities.org

**Comment by hugoruscitti** [comment]
Gracias @aurea1123 !!!, me alegra que piensen en la idea de hacer juegos.

Te comento que también pilas tiene una versión más nueva, llamada Pilas Engine 2, vas a poder encontrar más información en la web y en nuestro foro:

- https://pilas-engine.com.ar/videos/
- https://foro.pilas-engine.com.ar/

Cualquier duda que tengas mientras usas la herramienta buscame en el foro y voy
a tratar de ayudarte en lo que pueda.

Abrazo!!!

**Comment by aurea1123** [comment]
Una cosa se pueden incrustar en la web

**Comment by hugoruscitti** [comment]
Sí, la versión nueva sí. Se puede usar online, offline y exportarlo como html para poner en un iframe dentro de otra web o directamente en su propia página.

**Comment by aurea1123** [comment]
Vale gracias Me parece un proyecto buenismo ...
